name: Deploy Streamlit App to VPS

on:
  push:
    branches:
      - main # Déclenche le déploiement uniquement lors d'un push sur 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Déploiement via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/ubuntu/src/dash-yfinance
            git pull origin main
            .venv/bin/pip install -r requirements.txt
            sudo systemctl restart finance-dashboard.service
